# https://pre-commit.com/
repos:
  # https://github.com/astral-sh/ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        exclude: ^webmart_api/.*/migrations/
        files: ^webmart_api/.*\.py$