FROM python:3.12-slim-bullseye

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir gunicorn

COPY . .

EXPOSE 8000

ENV PYTHONPATH=/app/src

CMD ["gunicorn", "_webmart_api.wsgi:application", "--bind", "0.0.0.0:8000"]