# Generated by Django 5.2.1 on 2025-05-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Preparing'), (2, 'Shipped'), (1, 'Delivered'), (3, 'Cancelled')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='product.product')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.userprofile')),
            ],
        ),
    ]
